name: Deploy to Raspberry Pi 4

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/$GITHUB_ACTOR/test-actions
  CONTAINER_NAME: demo-go

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Loguearse en GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Construir imagen Docker multi-arch (arm64)
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64,linux/arm/v7 -t $IMAGE_NAME:latest --push .

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Loguearse en GHCR en la Raspberry Pi
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Descargar imagen Docker multi-arch (arm64) en la Raspberry Pi
        run: |
          kubectl apply -f manifests/deployment.yaml
          kubectl rollout restart deployment $CONTAINER_NAME
